// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUIKKzp5KLsALSi8lUyIc02JQoBBrdBXs',
    appId: '1:905229138938:web:22db5284acccc1591c8243',
    messagingSenderId: '905229138938',
    projectId: 'edda-1d0d8',
    authDomain: 'edda-1d0d8-1e665.firebaseapp.com',
    storageBucket: 'edda-1d0d8.appspot.com',
    measurementId: 'G-GEGP6THXXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApI5SS0mAhkawYKyRB9Te-xGC5pCBV9A0',
    appId: '1:905229138938:android:0c8cd37f53da355a1c8243',
    messagingSenderId: '905229138938',
    projectId: 'edda-1d0d8',
    storageBucket: 'edda-1d0d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAky_sLuHa1C4I2vXAzxdnJ16qyCloeYig',
    appId: '1:905229138938:ios:495348e6e2671d091c8243',
    messagingSenderId: '905229138938',
    projectId: 'edda-1d0d8',
    storageBucket: 'edda-1d0d8.appspot.com',
    iosBundleId: 'com.example.ekra',
  );
}
